name: jazzy

on:
  pull_request:
    branches:
      - jazzy-devel
  push:
    branches:
      - jazzy-devel

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-24.04]
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
        with:
          ref: jazzy-devel
      - name: Setup ROS 2
        uses: ros-tooling/setup-ros@0.7.15
        with:
          required-ros-distributions: jazzy
      - name: build and test
        uses: ros-tooling/action-ros-ci@0.4.5
        with:
          package-name: popf
          target-ros2-distro: jazzy
          colcon-defaults: |
            {
              "test": {
                "parallel-workers" : 1
              }
            }
          vcs-repo-file-url: 
          colcon-mixin-name: coverage-gcc
          colcon-mixin-repository: https://raw.githubusercontent.com/colcon/colcon-mixin-repository/master/index.yaml

